# Generated by Django 2.2 on 2020-07-04 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=150)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=150, verbose_name='Route Name')),
            ],
        ),
        migrations.CreateModel(
            name='BusUnit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID number:')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.BusStop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Route')),
            ],
        ),
    ]
