# Generated by Django 2.2 on 2020-07-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstop',
            old_name='adress',
            new_name='address',
        ),
    ]
