# Generated by Django 2.2 on 2020-07-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200704_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='zone',
            field=models.CharField(default='UFT', max_length=150),
        ),
    ]
