# Generated by Django 2.2 on 2020-07-16 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_busstop_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UFT', max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='busstop',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Zone'),
        ),
    ]
