# Generated by Django 2.2 on 2020-07-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20200715_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
