# Generated by Django 2.2 on 2020-07-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20200716_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busunit',
            name='location',
            field=models.ForeignKey(default='Central de operaciones', on_delete=django.db.models.deletion.SET_DEFAULT, to='API.BusStop'),
        ),
    ]
