# Generated by Django 2.2 on 2020-07-16 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20200716_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='stop1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada1', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada10', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada12', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop13',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada13', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop14',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada14', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop15',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada15', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop16',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada16', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop17',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada17', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop18',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada18', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop19',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada19', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada2', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop20',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada20', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada3', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada4', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada5', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada6', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada7', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada8', to='API.BusStop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stop9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada9', to='API.BusStop'),
        ),
        migrations.AlterField(
            model_name='busunit',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.BusStop'),
        ),
    ]
