# Generated by Django 2.2 on 2020-07-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20200716_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_description',
            field=models.CharField(default='No disponible', max_length=150, verbose_name='Route description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='route',
            field=models.CharField(default='No disponible', max_length=150, verbose_name='Route Name'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada1', to='API.BusStop', verbose_name='Route 1'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada10', to='API.BusStop', verbose_name='Route 10'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada12', to='API.BusStop', verbose_name='Route 12'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada13', to='API.BusStop', verbose_name='Route 13'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada14', to='API.BusStop', verbose_name='Route 14'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada15', to='API.BusStop', verbose_name='Route 15'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada16', to='API.BusStop', verbose_name='Route 16'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada17', to='API.BusStop', verbose_name='Route 17'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada18', to='API.BusStop', verbose_name='Route 18'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada19', to='API.BusStop', verbose_name='Route 19'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada2', to='API.BusStop', verbose_name='Route 2'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada20', to='API.BusStop', verbose_name='Route 20'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada3', to='API.BusStop', verbose_name='Route 3'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada4', to='API.BusStop', verbose_name='Route 4'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada5', to='API.BusStop', verbose_name='Route 5'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada6', to='API.BusStop', verbose_name='Route 6'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada7', to='API.BusStop', verbose_name='Route 7'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada8', to='API.BusStop', verbose_name='Route 8'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada9', to='API.BusStop', verbose_name='Route 9'),
        ),
    ]
