# Generated by Django 2.2 on 2020-07-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_zone_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Route Name'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
