# Generated by Django 2.2 on 2020-07-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_auto_20200716_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='stop12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada12', to='API.BusStop', verbose_name='Parada 12'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Parada11', to='API.BusStop', verbose_name='Parada 11'),
        ),
    ]
