# Generated by Django 2.2 on 2020-07-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_auto_20200719_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.BusStop')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.BusUnit')),
            ],
        ),
    ]
