# Generated by Django 2.2 on 2020-07-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0016_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
