# Generated by Django 2.2 on 2020-07-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0017_auto_20200721_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='datetime',
        ),
    ]
