# Generated by Django 2.2 on 2020-07-22 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0018_remove_register_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 21, 44, 29, 976562)),
        ),
    ]
